# Generated by Django 2.2.3 on 2019-07-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_commune', models.CharField(max_length=100, unique=True)),
                ('commune_name', models.TextField(max_length=100)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='Activo', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100, unique=True)),
                ('commune', models.ManyToManyField(to='regions.Commune')),
            ],
        ),
    ]
